version: 2

jobs:
  build:
    build:
    docker:
       - image: docker.palantir.build/circle2-build-images/ubuntu-jdk-npm:0.19.0
    working_directory: ~/project
    environment:
      DOCKER_SINK=sandbox.docker.palantir.build/rbergeron
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build images
          command: ./build.sh
      - run:
          name: export to iso
          command: |
            docker create -v /workdir --name workdir alpine:3.4 /bin/true
            docker run --volumes-from workdir build/xenial-installer
      - run:
          name: publish iso
          command: |
            docker cp workdir:/workdir/installercore.iso installercore.iso
            ./publish.sh
