version: 2

jobs:
  build:
    docker:
      - image: sandbox.docker.palantir.build/rbergeron/dind
    working_directory: /project
    environment:
      DOCKER_SINK=sandbox.docker.palantir.build/rbergeron
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build images
          command: ./build.sh
      - run:
          name: export to iso
          command: docker run --rm=true -v "$(pwd):/workdir" build/xenial-installer
